package com.teamabnormals.atmospheric.core.other;

import net.minecraft.data.BlockFamily;

import static com.teamabnormals.atmospheric.core.registry.AtmosphericBlocks.*;

public class AtmosphericBlockFamilies {
	public static final BlockFamily ROSEWOOD_PLANKS_FAMILY = new BlockFamily.Builder(ROSEWOOD_PLANKS.get()).button(ROSEWOOD_BUTTON.get()).fence(ROSEWOOD_FENCE.get()).fenceGate(ROSEWOOD_FENCE_GATE.get()).pressurePlate(ROSEWOOD_PRESSURE_PLATE.get()).sign(ROSEWOOD_SIGNS.getFirst().get(), ROSEWOOD_SIGNS.getSecond().get()).slab(ROSEWOOD_SLAB.get()).stairs(ROSEWOOD_STAIRS.get()).door(ROSEWOOD_DOOR.get()).trapdoor(ROSEWOOD_TRAPDOOR.get()).recipeGroupPrefix("wooden").recipeUnlockedBy("has_planks").getFamily();
	public static final BlockFamily MORADO_PLANKS_FAMILY = new BlockFamily.Builder(MORADO_PLANKS.get()).button(MORADO_BUTTON.get()).fence(MORADO_FENCE.get()).fenceGate(MORADO_FENCE_GATE.get()).pressurePlate(MORADO_PRESSURE_PLATE.get()).sign(MORADO_SIGNS.getFirst().get(), MORADO_SIGNS.getSecond().get()).slab(MORADO_SLAB.get()).stairs(MORADO_STAIRS.get()).door(MORADO_DOOR.get()).trapdoor(MORADO_TRAPDOOR.get()).recipeGroupPrefix("wooden").recipeUnlockedBy("has_planks").getFamily();
	public static final BlockFamily YUCCA_PLANKS_FAMILY = new BlockFamily.Builder(YUCCA_PLANKS.get()).button(YUCCA_BUTTON.get()).fence(YUCCA_FENCE.get()).fenceGate(YUCCA_FENCE_GATE.get()).pressurePlate(YUCCA_PRESSURE_PLATE.get()).sign(YUCCA_SIGNS.getFirst().get(), YUCCA_SIGNS.getSecond().get()).slab(YUCCA_SLAB.get()).stairs(YUCCA_STAIRS.get()).door(YUCCA_DOOR.get()).trapdoor(YUCCA_TRAPDOOR.get()).recipeGroupPrefix("wooden").recipeUnlockedBy("has_planks").getFamily();
	public static final BlockFamily ASPEN_PLANKS_FAMILY = new BlockFamily.Builder(ASPEN_PLANKS.get()).button(ASPEN_BUTTON.get()).fence(ASPEN_FENCE.get()).fenceGate(ASPEN_FENCE_GATE.get()).pressurePlate(ASPEN_PRESSURE_PLATE.get()).sign(ASPEN_SIGNS.getFirst().get(), ASPEN_SIGNS.getSecond().get()).slab(ASPEN_SLAB.get()).stairs(ASPEN_STAIRS.get()).door(ASPEN_DOOR.get()).trapdoor(ASPEN_TRAPDOOR.get()).recipeGroupPrefix("wooden").recipeUnlockedBy("has_planks").getFamily();
	public static final BlockFamily LAUREL_PLANKS_FAMILY = new BlockFamily.Builder(LAUREL_PLANKS.get()).button(LAUREL_BUTTON.get()).fence(LAUREL_FENCE.get()).fenceGate(LAUREL_FENCE_GATE.get()).pressurePlate(LAUREL_PRESSURE_PLATE.get()).sign(LAUREL_SIGNS.getFirst().get(), LAUREL_SIGNS.getSecond().get()).slab(LAUREL_SLAB.get()).stairs(LAUREL_STAIRS.get()).door(LAUREL_DOOR.get()).trapdoor(LAUREL_TRAPDOOR.get()).recipeGroupPrefix("wooden").recipeUnlockedBy("has_planks").getFamily();
	public static final BlockFamily KOUSA_PLANKS_FAMILY = new BlockFamily.Builder(KOUSA_PLANKS.get()).button(KOUSA_BUTTON.get()).fence(KOUSA_FENCE.get()).fenceGate(KOUSA_FENCE_GATE.get()).pressurePlate(KOUSA_PRESSURE_PLATE.get()).sign(KOUSA_SIGNS.getFirst().get(), KOUSA_SIGNS.getSecond().get()).slab(KOUSA_SLAB.get()).stairs(KOUSA_STAIRS.get()).door(KOUSA_DOOR.get()).trapdoor(KOUSA_TRAPDOOR.get()).recipeGroupPrefix("wooden").recipeUnlockedBy("has_planks").getFamily();
	public static final BlockFamily GRIMWOOD_PLANKS_FAMILY = new BlockFamily.Builder(GRIMWOOD_PLANKS.get()).button(GRIMWOOD_BUTTON.get()).fence(GRIMWOOD_FENCE.get()).fenceGate(GRIMWOOD_FENCE_GATE.get()).pressurePlate(GRIMWOOD_PRESSURE_PLATE.get()).sign(GRIMWOOD_SIGNS.getFirst().get(), GRIMWOOD_SIGNS.getSecond().get()).slab(GRIMWOOD_SLAB.get()).stairs(GRIMWOOD_STAIRS.get()).door(GRIMWOOD_DOOR.get()).trapdoor(GRIMWOOD_TRAPDOOR.get()).recipeGroupPrefix("wooden").recipeUnlockedBy("has_planks").getFamily();


	public static final BlockFamily DOLERITE_FAMILY = new BlockFamily.Builder(DOLERITE.get()).slab(DOLERITE_SLAB.get()).stairs(DOLERITE_STAIRS.get()).wall(DOLERITE_WALL.get()).getFamily();
	public static final BlockFamily POLISHED_DOLERITE_FAMILY = new BlockFamily.Builder(POLISHED_DOLERITE.get()).slab(POLISHED_DOLERITE_SLAB.get()).stairs(POLISHED_DOLERITE_STAIRS.get()).getFamily();

	public static final BlockFamily ARID_SANDSTONE_FAMILY = new BlockFamily.Builder(ARID_SANDSTONE.get()).wall(ARID_SANDSTONE_WALL.get()).stairs(ARID_SANDSTONE_STAIRS.get()).slab(ARID_SANDSTONE_SLAB.get()).chiseled(CHISELED_ARID_SANDSTONE.get()).cut(CUT_ARID_SANDSTONE.get()).dontGenerateRecipe().getFamily();
	public static final BlockFamily CUT_ARID_SANDSTONE_FAMILY = new BlockFamily.Builder(CUT_ARID_SANDSTONE.get()).slab(CUT_ARID_SANDSTONE_SLAB.get()).getFamily();
	public static final BlockFamily SMOOTH_ARID_SANDSTONE_FAMILY = new BlockFamily.Builder(SMOOTH_ARID_SANDSTONE.get()).slab(SMOOTH_ARID_SANDSTONE_SLAB.get()).stairs(SMOOTH_ARID_SANDSTONE_STAIRS.get()).getFamily();
	public static final BlockFamily ARID_SANDSTONE_BRICKS_FAMILY = new BlockFamily.Builder(ARID_SANDSTONE_BRICKS.get()).wall(ARID_SANDSTONE_BRICK_WALL.get()).stairs(ARID_SANDSTONE_BRICK_STAIRS.get()).slab(ARID_SANDSTONE_BRICK_SLAB.get()).dontGenerateRecipe().getFamily();
	public static final BlockFamily RED_ARID_SANDSTONE_FAMILY = new BlockFamily.Builder(RED_ARID_SANDSTONE.get()).wall(RED_ARID_SANDSTONE_WALL.get()).stairs(RED_ARID_SANDSTONE_STAIRS.get()).slab(RED_ARID_SANDSTONE_SLAB.get()).chiseled(CHISELED_RED_ARID_SANDSTONE.get()).cut(CUT_RED_ARID_SANDSTONE.get()).dontGenerateRecipe().getFamily();
	public static final BlockFamily CUT_RED_ARID_SANDSTONE_FAMILY = new BlockFamily.Builder(CUT_RED_ARID_SANDSTONE.get()).slab(CUT_RED_ARID_SANDSTONE_SLAB.get()).getFamily();
	public static final BlockFamily SMOOTH_RED_ARID_SANDSTONE_FAMILY = new BlockFamily.Builder(SMOOTH_RED_ARID_SANDSTONE.get()).slab(SMOOTH_RED_ARID_SANDSTONE_SLAB.get()).stairs(SMOOTH_RED_ARID_SANDSTONE_STAIRS.get()).getFamily();
	public static final BlockFamily RED_ARID_SANDSTONE_BRICKS_FAMILY = new BlockFamily.Builder(RED_ARID_SANDSTONE_BRICKS.get()).wall(RED_ARID_SANDSTONE_BRICK_WALL.get()).stairs(RED_ARID_SANDSTONE_BRICK_STAIRS.get()).slab(RED_ARID_SANDSTONE_BRICK_SLAB.get()).dontGenerateRecipe().getFamily();
}